spring.application.name=job-agent
spring.datasource.url=jdbc:postgresql://localhost:5432/jobagentdb?serverTimezone=UTC
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD_HERE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect