

services:
  postgres:
    image: postgres:latest
    container_name: job-agent-db
    environment:
      POSTGRES_DB: jobagentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sikhar123
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: